FROM golang:latest

# Install dependencies
# Should `go get` locally before building
# to update mod and sum files
WORKDIR /app
COPY ./backend/go.mod ./backend/go.sum ./
RUN go get

# Install hot reloading
RUN go get github.com/codegangsta/gin

EXPOSE 8080
CMD gin --immediate app.go